# Site settings
title: "Adarsh's Pentesting Blog"
email: "your-email@example.com"
description: >- 
  A blog documenting my journey in penetration testing, red teaming, 
  and cybersecurity. Follow for write-ups, tutorials, and insights.
baseurl: ""  # Keep empty unless using a subdirectory
url: "https://yourusername.github.io"  # Replace with your actual GitHub Pages URL
twitter_username: "your_twitter_handle"
github_username: "your_github_username"

# Theme settings
remote_theme: jekyll/minima  # Use Minima as the GitHub Pages theme

# Plugins (GitHub Pages-supported)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Pagination settings
paginate: 5  # Number of posts per page
paginate_path: "/page:num/"

# Exclude from processing (performance optimization)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Permalinks (optional: for SEO-friendly URLs)
permalink: pretty

# SEO and social settings
author: "Adarsh"  # Your name or pseudonym
keywords: "penetration testing, cybersecurity, red teaming, ethical hacking"
timezone: "UTC"

# Markdown processor
markdown: kramdown
